---
# defaults file for docker_buildnode
docker_required_packages:
  - git
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

# See https://github.com/rancher/install-docker for available versions.
docker_version: "19.03"
