apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:privileged
  namespace: ipfailover
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - unrestricted-psp
    resources:
      - podsecuritypolicy
    verbs:
      - use
