---

- name: Install firewalld
  yum:
    name: "firewalld"
    state: present
  when: enable_firewalld

- name: Enable and start firewalld
  systemd:
    state: started
    name: firewalld
    enabled: yes
  when: enable_firewalld

- name: Configure Firewall
  import_tasks: firewall.yml
  when: manage_rancher_related_firewalld_rules
